name: molscore_minimal
channels:
  - anaconda
  - conda-forge
  - openeye
  - pytorch
  - nvidia
dependencies:
  - python>=3.8
  - rdkit>=2019.03.2
  - ipython
  - prolif 
  - openeye-toolkits
  - smina=2017.11.9
  - openbabel
  - dask 
  - py-xgboost
  - streamlit>=1.11.0
  - pytorch
  - pytorch-cuda=11.6
  - pip
  - pip:
    - zenodo-client 
    - levenshtein
    - streamlit-plotly-events
