name: molscore_minimal
channels:
  - anaconda
  - conda-forge
  - openeye
  - pytorch
  - nvidia
dependencies:
  - python>=3.8,<3.10
  - rdkit>=2019.03.2
  - ipython
  - prolif 
  - openeye-toolkits
  - smina=2017.11.9
  - openbabel
  - dask
  - pytorch::pytorch
  - pytorch::torchvision
  - pytorch::torchaudio
  - pytorch::pytorch-cuda=11.6  # Version may need to change depending on NVIDIA drivers
  - pip
  - pip:
    - zenodo-client==0.2.0
    - levenshtein
    - streamlit-plotly-events
    - streamlit>=1.11.0
    - molbloom
