name: moleval
channels:
  - rdkit
  - conda-forge
  - bioconda
  - defaults
  - openeye
  - pytorch
dependencies:
  - python
  - ipython
  - jupyter
  - nb_conda
  - rdkit
  - numpy
  - pandas
  - matplotlib
  - pip
  - scipy
  - seaborn
  - setuptools
  - tqdm
  - umap-learn
  - pytorch=1.4.0=py3.7_cuda10.1.243_cudnn7.6.3_0
  - torchvision=0.5.0=py37_cu101
  - pip:
      - importlib-resources
      - faerun
      - fcd-torch==1.0.7
      - faerun
