name: molscore
channels:
  - rdkit
  - conda-forge
  - bioconda
  - defaults
  - openeye
  - omnia
dependencies:
  - python=3.6
  - ipython
  - rdkit
  - dash
  - dash-bio
  - dask
  - numpy
  - pandas
  - matplotlib
  - openeye-toolkits
  - pip
  - scipy
  - seaborn
  - setuptools
  - tqdm
  - wheel
  - parmed
  - openbabel
  - smina
  - qvina
  - streamlit
  - bokeh=2.2
  - py3dmol
  - xgboost
  - pip:
      - importlib-resources
      - streamlit-bokeh-events
